name: dictionarylib
description: "Library for the sign language dictionary apps"
version: 0.0.16

publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider:
  collection:
  cupertino_icons:
  device_info_plus:
  dolphinsr_dart:
    git:
      url: https://github.com/banool/dolphhinsr_dart.git
      ref: master
  dots_indicator:
  edit_distance: ^0.5.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_cache_manager:
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_native_splash: 2.3.10
  go_router: 6.5.9
  http:
  intl:
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  launch_review:
  mailto:
  multi_select_flutter:
  package_info_plus:
  path_provider:
  settings_ui:
  shared_preferences:
  system_proxy:
  url_launcher:
  video_player:

dev_dependencies:
  build_runner: ^2.3.3
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints:

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
